// <auto-generated />
using System;
using CMS_Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS_Infrastructure.Migrations
{
    [DbContext(typeof(ComputerVisionContext))]
    partial class ComputerVisionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CMS_WebDesignCore.Entities.CanCuocCongDan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("ChinhXac")
                        .HasColumnType("bit");

                    b.Property<string>("DacDiemNhanDang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoChinhXacDacDiemNhanDang")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacDiaChiThuongTru")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacGioiTinh")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacHoTen")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacNgayCap")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacNgayHetHan")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacNgaySinh")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacQueQuan")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacQuocTich")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacSo")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacVnm")
                        .HasColumnType("int");

                    b.Property<int>("DuLieuId")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayHetHan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("So")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnm")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DuLieuId");

                    b.ToTable("CanCuocCongDans");
                });

            modelBuilder.Entity("CMS_WebDesignCore.Entities.DuLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("MatSau")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("MatTruoc")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DuLieus");
                });

            modelBuilder.Entity("CMS_WebDesignCore.Entities.GiayPhepLaiXe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("ChinhXac")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoChinhXacDiaChi")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacGioiTinh")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacHang")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacHoTen")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacNgayDangKi")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacNgaySinh")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacNgayTrungTuyen")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacPhuongTienDuocPhep")
                        .HasColumnType("int");

                    b.Property<int?>("DoChinhXacSo")
                        .HasColumnType("int");

                    b.Property<int>("DuLieuId")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayDangKi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayTrungTuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongTienDuocPhep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("So")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DuLieuId");

                    b.ToTable("GiayPhepLaiXes");
                });

            modelBuilder.Entity("CMS_WebDesignCore.Entities.CanCuocCongDan", b =>
                {
                    b.HasOne("CMS_WebDesignCore.Entities.DuLieu", "DuLieu")
                        .WithMany()
                        .HasForeignKey("DuLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuLieu");
                });

            modelBuilder.Entity("CMS_WebDesignCore.Entities.GiayPhepLaiXe", b =>
                {
                    b.HasOne("CMS_WebDesignCore.Entities.DuLieu", "DuLieu")
                        .WithMany()
                        .HasForeignKey("DuLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuLieu");
                });
#pragma warning restore 612, 618
        }
    }
}
