export const content = [{
  key: "T6",
  title: "T6 - Nhận dạng thẻ 🚀",
  subtitle: "Giới thiệu sản phẩm: Hệ thống Nhận dạng Giấy tờ Cá nhân và Bóc tách Thông tin.",
  content: ["Xin chào! Chúng tôi xin giới thiệu đến bạn một sản phẩm trong lĩnh vực công nghệ thông tin - Hệ thống Nhận dạng Giấy tờ Cá nhân và Bóc tách Thông tin. Đây là một giải pháp hiệu quả và đáng tin cậy giúp tự động nhận dạng các loại giấy tờ cá nhân và trích xuất thông tin từ chúng một cách nhanh chóng và chính xác.", "Sứ mệnh của chúng tôi là giúp giảm thiểu công sức và thời gian của con người trong việc xử lý hàng nghìn giấy tờ cá nhân hàng ngày. Với công nghệ tiên tiến, sản phẩm của chúng tôi có khả năng phân tích, nhận dạng và bóc tách thông tin từ các loại giấy tờ cá nhân như thẻ căn cước, giấy phép lái xe.", "Hệ thống Nhận dạng Giấy tờ Cá nhân và Bóc tách Thông tin sử dụng các rule nhận dạng và công nghệ xử lý hình ảnh bằng Google Vision để tự động nhận dạng và trích xuất nội dung toàn văn từ giấy tờ cá nhân.", "Sản phẩm của chúng tôi không chỉ đảm bảo tính chính xác cao trong việc nhận dạng thông tin từ giấy tờ cá nhân mà còn có khả năng xử lý hàng loạt, cho phép bạn xử lý hàng trăm hoặc thậm chí hàng ngàn tài liệu trong thời gian ngắn. Điều này giúp tiết kiệm thời gian và tăng năng suất công việc đáng kể, đồng thời giảm thiểu sai sót và rủi ro liên quan đến việc xử lý thủ công.", "Hệ thống Nhận dạng Giấy tờ Cá nhân và Bóc tách Thông tin của chúng tôi có thể tích hợp vào các ứng dụng và hệ thống tự động hiện có của bạn. Bất kể bạn là một tổ chức tài chính, công ty bảo hiểm, cơ quan chính phủ hoặc bất kỳ tổ chức nào cần xử lý và quản lý thông tin cá nhân, sản phẩm của chúng tôi sẽ đáp ứng được nhu cầu của bạn một cách linh hoạt và đáng tin cậy.", "Cảm ơn bạn đã dành thời gian để tìm hiểu về sản phẩm của chúng tôi. Chúng tôi hy vọng rằng hệ thống Nhận dạng Giấy tờ Cá nhân và Bóc tách Thông tin sẽ là một công cụ hữu ích và giá trị cho bạn và tổ chức của bạn."],
  linkdemo: "https://www.youtube.com/embed/z0KErzaQ0es",
},
{
  key: "T7.1",
  title: "T7 - ChatBot DMT du lịch Việt 🔒",
  subtitle: "Giới thiệu sản phẩm: Chatbot Hướng dẫn Du lịch thông minh.",
  content: ["Xin chào! Chúng tôi xin giới thiệu đến bạn một công nghệ trong lĩnh vực du lịch - Chatbot Hướng dẫn Du lịch thông minh. Đây là một sản phẩm sáng tạo được phát triển để cung cấp thông tin và hướng dẫn du lịch tận hưởng và khám phá các địa điểm du lịch trên toàn thế giới một cách dễ dàng và tiện lợi.", "Sứ mệnh của chúng tôi là tạo ra một trợ lý du lịch ảo thông minh, một chatbot có khả năng trò chuyện và cung cấp thông tin chi tiết, gợi ý và lời khuyên về các điểm đến du lịch. Chatbot Hướng dẫn Du lịch thông minh của chúng tôi sử dụng trí tuệ nhân tạo để hiểu và phản hồi các câu hỏi và yêu cầu của người dùng một cách tự nhiên và chính xác.", "Với Chatbot Hướng dẫn Du lịch thông minh, bạn có thể nhận được thông tin về các địa điểm du lịch nổi tiếng, như danh lam thắng cảnh, di sản văn hóa, những địa điểm ẩm thực hấp dẫn và nhiều hơn nữa. Chatbot có thể cung cấp thông tin về lịch trình du lịch, khuyến nghị hoạt động và trải nghiệm thú vị tại từng điểm đến. Ngoài ra, nó còn có thể đề xuất các chương trình du lịch phù hợp với sở thích và ngân sách của bạn.", "Chatbot Hướng dẫn Du lịch thông minh của chúng tôi cũng cung cấp thông tin về khách sạn, nhà hàng, cửa hàng mua sắm và dịch vụ du lịch khác tại các địa điểm du lịch. Bạn có thể tìm kiếm và đặt chỗ trực tuyến, nhận thông tin về giá cả, đánh giá và đề xuất dựa trên những đánh giá từ du khách khác.", "Cảm ơn bạn đã dành thời gian để tìm hiểu về sản phẩm của chúng tôi. Chúng tôi hy vọng rằng Chatbot Hướng dẫn Du lịch thông minh sẽ mang lại cho bạn trải nghiệm du lịch tuyệt vời và giúp bạn khám phá những điểm đến mới một cách dễ dàng và thú vị."],
  linkdemo: "https://www.youtube.com/embed/z0KErzaQ0es",
},
{
  key: "T7.2",
  title: "T7 - AI dịch tài liệu đa dinh dạng (EN-KR-JP) 🔒",
  subtitle: "Giới thiệu sản phẩm: Dịch tài liệu PDF, Excel, Word, PowerPoint và xuất ra hình ảnh đã dịch từng trang.",
  content: ["Xin chào! Chúng tôi xin giới thiệu đến bạn một công nghệ đột phá trong lĩnh vực dịch tài liệu - Sản phẩm Dịch tài liệu PDF, Excel, Word, PowerPoint và xuất ra hình ảnh đã dịch từng trang. Đây là một giải pháp tiên tiến và thuận tiện để dịch các tài liệu văn bản chính xác và nhanh chóng từ định dạng PDF, Excel, Word và PowerPoint sang hình ảnh đã dịch.", "Sứ mệnh của chúng tôi là giúp bạn dễ dàng chuyển đổi và dịch các tài liệu văn bản sang ngôn ngữ mong muốn một cách nhanh chóng và hiệu quả. Sản phẩm của chúng tôi sử dụng công nghệ dịch máy thông minh và xử lý hình ảnh để nhận diện và dịch các văn bản trong tài liệu. Bạn chỉ cần tải lên tài liệu của mình và chọn ngôn ngữ đích, sau đó sản phẩm sẽ tự động xử lý, dịch và xuất ra hình ảnh đã dịch từng trang.", "Với Sản phẩm Dịch tài liệu PDF, Excel, Word, PowerPoint và xuất ra hình ảnh đã dịch từng trang của chúng tôi, bạn có thể dễ dàng chuyển đổi các tài liệu quan trọng, báo cáo, hợp đồng, tài liệu học tập và nhiều loại tài liệu khác sang ngôn ngữ mà bạn mong muốn. Bạn không cần phải tự mình dịch hoặc tìm kiếm dịch giả, tiết kiệm thời gian và công sức đáng kể.", "Sản phẩm của chúng tôi hỗ trợ nhiều ngôn ngữ phổ biến và có khả năng xử lý các định dạng tài liệu phổ biến như PDF, Excel, Word và PowerPoint.", "Cảm ơn bạn đã dành thời gian để tìm hiểu về sản phẩm của chúng tôi. Chúng tôi hy vọng rằng Sản phẩm Dịch tài liệu PDF, Excel, Word, PowerPoint và xuất ra hình ảnh đã dịch từng trang sẽ là một công cụ hữu ích và giá trị trong quá trình làm việc và trao đổi thông tin."],
  linkdemo: "https://www.youtube.com/embed/z0KErzaQ0es",
}];